CREATE TABLE fantasystats AS
SELECT nbastats.*, stlblk.sum                                                                                                                          
from nbastats, stlblk
where nbastats.player = stlblk.player;

SELECT player, pts, stl, ast
FROM fantasystats
WHERE pts > 18 AND stl > 2;

SELECT player, trb
FROM fantasystats
ORDER BY trb desc
limit 10;

SELECT player, ast, blk
FROM fantasystats
WHERE ast >= 7
ORDER BY blk desc
LIMIT 10;